version: '3'

services:
  web:
    image: php:8.2-apache
    container_name: moodle45_web
    ports:
      - "8080:80"
    volumes:
      - moodle-data:/var/www/html
      - ./wait-for-db.sh:/wait-for-db.sh  # Adicionando o script
    environment:
      - PHP_MEMORY_LIMIT=512M
    depends_on:
      - db
    entrypoint: ["sh", "/wait-for-db.sh", "apache2-foreground"]  # Espera pelo banco de dados antes de iniciar o Apache

  db:
    image: mariadb:10.6.7
    container_name: moodle45_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle45
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepassword
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  moodle-data:
  mariadb-data:
