version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/moodledata45
    environment:
      - PHP_MEMORY_LIMIT=512M
    networks:
      - moodlenetwork

  db:
    image: mariadb:10.6.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle45
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepassword
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - moodlenetwork

volumes:
  mariadb-data:

networks:
  moodlenetwork:
 